version: '3'

services:
  webserver:
    build:
      context: ./portfolio-app
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "80:80"
      - "443:443"
    restart: always
