name: Backend CI

on:
  push:
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Build with Maven
      working-directory: server
      run: mvn clean install

    - name: Test with Maven
      working-directory: server
      run: mvn test

